image: node:latest

before_script:
  - pwd
  - which nodejs
  - nodejs -v
  - which npm
  - npm -v
  - which yarn
  - yarn --version

cache:
  paths:
    - node_modules/

stages:
  - install_dependencies
  - test
  - publish

install_dependencies:
  script:
    - yarn install
  stage: install_dependencies
  artifacts:
    paths:
      - node_modules/

test:
  script:
    - yarn run type:check
    - yarn run lint
    - yarn run test
  stage: test
  only:
    - develop
    - tags

publish:
  script:
    - yarn run build:remove
    - yarn run build
    - echo NPT_TOKEN is ${NPM_TOKEN}
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - cat .npmrc
    - npm publish
  stage: publish
  only:
    - tags
