image:
  name: node:10.16.3

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - pwd
  - which nodejs
  - nodejs -v
  - which npm
  - npm -v
  - which yarn
  - yarn --version

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - install_dependencies
  - test
  - publish
  - deploy

install_dependencies:
  script:
    - yarn install
  stage: install_dependencies
  only:
    - develop
    - tags

test:
  script:
    - yarn run type:check
    - yarn run lint
    - yarn run test
  stage: test
  only:
    - develop
    - tags

publish:
  script:
    - yarn run build:remove
    - yarn run build
    - echo NPT_TOKEN is ${NPM_TOKEN}
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' > .npmrc
    - cat .npmrc
    - npm publish
  stage: publish
  only:
    - tags

pages:
  script:
    - yarn run build:doc
    - rm -rf public
    - mv docs public
    - ls -al public
  stage: deploy
  only:
    - tags
  artifacts:
    paths:
      - public
